version: '3'

services:
  typebeast-client:
    build: ./client
    volumes:
      - ./client:/user/src/app:rw
      - /usr/src/app/node_modules/
    ports: 
     - 3000:3000
  typebeast-server:
    build: ./typeserver
    volumes:
      - ./server:/usr/src/app:rw
      - /usr/src/app/node_modules/
    ports:
      - 8081:8081
      - 8000:8000